In [3]:
# Print alternate elements of a list
lst = input("Enter elements of the list separated by spaces: ").split()
print(lst[::2])

Enter elements of the list separated by spaces: my name is muzammil ansari
['my', 'is', 'ansari']

In [7]:
# Reverse the contents of a list without using reverse()
lst = input("Enter elements of the list separated by spaces: ").split()
reversed_lst = lst[::-1]
print(reversed_lst)

Enter elements of the list separated by spaces: my name is muzammil ansari
['ansari', 'muzammil', 'is', 'name', 'my']

In [8]:

# Find the largest number in a list without using max()
lst = list(map(int, input("Enter numbers separated by spaces: ").split()))
largest = lst[0]
for num in lst:
    if num > largest:
        largest = num
print(largest)

Enter numbers separated by spaces: 12 343 53
343

In [11]:
# Rotate elements of a list
lst = input("Enter elements of the list separated by spaces: ").split()
rotated_lst = lst[1:] + lst[:1]
print(rotated_lst)

Enter elements of the list separated by spaces: i am a student
['am', 'a', 'student', 'i']

In [12]:
# Delete a word from a string
string = input("Enter a string: ")
word_to_remove = input("Enter the word to delete: ")
new_string = string.replace(word_to_remove, "").strip()
print(new_string)

Enter a string: i a very happy
Enter the word to delete: a
i  very hppy

In [15]:
# Convert a date from mm/dd/yyyy to Month day, year
import datetime
date_str = input("Enter a date in mm/dd/yyyy format: ")
date_obj = datetime.datetime.strptime(date_str, "%m/%d/%Y")
formatted_date = date_obj.strftime("%B %d, %Y")
print(formatted_date)

Enter a date in mm/dd/yyyy format: 01/22/2022
January 22, 2022

In [16]:
# Capitalize each word in a string
def capitalize_words(s):
    return ' '.join(word.capitalize() for word in s.split())

sentence = input("Enter a sentence: ")
print(capitalize_words(sentence))

Enter a sentence: i am so happy
I Am So Happy

In [28]:
# Sum of each row in a matrix
m, n = map(int, input("Enter the number of rows and columns (m n): ").split())
matrix = []
for i in range(m):
    row = list(map(int, input(f"Enter elements of row {i+1}: ").split()))
    matrix.append(row)

for i in range(m):
    print(f"Sum of row {i+1} =", sum(matrix[i]))

Enter the number of rows and columns (m n): 3 3
Enter elements of row 1: 3 5 6
Enter elements of row 2: 1 2 3
Enter elements of row 3: 4 5 6
Sum of row 1 = 14
Sum of row 2 = 6
Sum of row 3 = 15

In [27]:
# Add two matrices of size m x n
m, n = map(int, input("Enter the number of rows and columns (m n): ").split())
print("Enter elements of first matrix:")
matrix1 = [list(map(int, input().split())) for _ in range(m)]
print("Enter elements of second matrix:")
matrix2 = [list(map(int, input().split())) for _ in range(m)]

result = [[matrix1[i][j] + matrix2[i][j] for j in range(n)] for i in range(m)]
print("Resultant matrix:")
for row in result:
    print(' '.join(map(str, row)))

Enter the number of rows and columns (m n): 2 2
Enter elements of first matrix:
1 2
3 4
Enter elements of second matrix:
5 6
7 8
Resultant matrix:
6 8
10 12

In [26]:
# Multiply two matrices
m, n = map(int, input("Enter rows and columns of first matrix (m n): ").split())
p = int(input("Enter number of columns for second matrix: "))
print("Enter elements of first matrix:")
matrix1 = [list(map(int, input().split())) for _ in range(m)]
print("Enter elements of second matrix:")
matrix2 = [list(map(int, input().split())) for _ in range(n)]

result = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(n)) for j in range(p)] for i in range(m)]
print("Resultant matrix:")
for row in result:
    print(' '.join(map(str, row)))

Enter rows and columns of first matrix (m n): 2 3
Enter number of columns for second matrix: 2
Enter elements of first matrix:
1 2 3
4 5 6
Enter elements of second matrix:
7 8
9 10
11 12
Resultant matrix:
58 64
139 154